### ISSUE TITLE
Is settle escrow payment still a feature?

### ISSUE THREAD

**Issue by dawoodjee** [Flutterwave/rave-python#93]
The [rave v2 docs clearly show](https://developer.flutterwave.com/v2.0/docs/escrow-payments#settling-an-escrow-payment) that the endpoint `https://api.ravepay.co/v2/gpx/transactions/escrow/settle` should settle a pending escrow payment, however, a 404 error comes up instead.

I've tried using `https://rave.flutterwave.com` and `https://ravesandbox.flutterwave.com`

No docs I can find show the right right way to settle escrow payment. Please help!

**Comment by Corvus97** [comment]
Hello @dawoodjee,

Thanks for sharing this with the team.

Kindly note that the 404 error reported will only be returned for two reasons:

1. Non-existent escrow transaction IDs. This happens when the meta array initiating the escrow is not passed in the initial payment.  Kindly cross-check with the developer docs and confirm that the right meta parameter is passed.
2. Wrong ID passed in the settle endpoint. Please note that the id to be sent in the settle endpoint is returned as data.txid in the verify response for the initial escrow charge. any other value would return 404.

We'd also like to point out that the feature is not supported in the SDK. If you would like to make use of this, Please consider consuming the API directly.

Let us know if you have any questions.

**Comment by dawoodjee** [comment]
Hello Cornelius

Thank you for your quick response. I apologize for asking here but I'm quite desperate. 

It seems like this endpoint does not exist. Looking at the response when a valid endpoint is reached, vs when it isn't. Valid endpoints always return JSON, whereas invalid ones show `Cannot Get [your query]`

![image](https://user-images.githubusercontent.com/7912989/146881256-5369d7e5-1d10-4754-8ce0-9229fd2da7c3.png)
Valid Endpoint

![image](https://user-images.githubusercontent.com/7912989/146882474-55f7bab5-9879-4ef2-96e6-2f2994c271be.png)
Valid Endpoint with error

![image](https://user-images.githubusercontent.com/7912989/146882583-9807600e-ac7f-4126-96e6-2bf8838efe4f.png)
Same endpoint with a typo

![image](https://user-images.githubusercontent.com/7912989/146881288-a9115450-5135-4e3f-aead-62325fa17402.png)
Escrow endpoint seems invalid, it also gives the same result if I pass the parameters

**Comment by dawoodjee** [comment]
I've resolved this issue by specifying that the request type is POST not the default GET.

Thank you
